import matplotlib.pyplot as plt
import numpy as np
fs=input('Enter value for fs:')
f=input('Enter value for f:')
x=np.arange(0,100,1)
y1=np.sin(2*np.pi*f*x/fs)
y2=np.cos(2*np.pi*f*x/fs)
y=y1+y2
plt.subplot(1,3,1)
plt.plot(x,y1)
plt.tittle('sin wave')
plt.xlabel('------------->t')
plt.y1label('------------>voltage')
plt.subplot(1,3,2)
plt.plot(x,y2)
plt.tittle('cos wave')
plt.xlabel('------------->t')
plt.y2label('------------>voltage')
plt.subplot(1,3,3)
plt.plot(x,y)
plt.tittle('sin wave and cos wave')
plt.xlabel('------------->t')
plt.ylabel('------------>voltage')
plt.show()
