import matplotlib.pyplot as plt
import numpy as np
fs=input('Enter value for fs:')
fs1=input('Enter value for fs1:')
f=input('Enter value for f:')
f1=input('Enter value for f1:')
x=np.arange(0,100,1)
q=np.sin(2*np.pi*f*x/fs)
p=np.cos(2*np.pi*f1*x/fs1)
y=q+p
plt.subplot(1,3,1)
plt.plot(x,q)
plt.title('sin wave')
plt.xlabel('t')
plt.ylabel('voltage')
plt.subplot(1,3,2)
plt.plot(x,p)
plt.title('cos wave')
plt.xlabel('t')
plt.ylabel('voltage')
plt.subplot(1,3,3)
plt.plot(x,y)
plt.title('sin wave and cos wave')
plt.xlabel('t')
plt.ylabel('voltage')
plt.show()
